### ISSUE TITLE
((( atom ))) Installations Anleitung

### ISSUE THREAD

**Issue by mr-berndt** [GittyBaer/MPV-HKV-Configs-HowTos#1]
Hallo,

((( atom ))) hier.
Ich würde mich freuen, wenn die "HKV-Anleitung" zumindest in ((( atom ))) s Anleitung umbenannt werden würde. Ich mache das zwar gerne für die Allgemeinheit, aber dem HKV gehört die sicherlich nicht. War auch bestimmt nicht böse gemeint, mir schon klar.

Evtl. mach ich hier ein wenig mit.

Sollte man das Ding evtl. auf Englisch machen?

**Comment by GittyBaer** [comment]
Hi,
können wir machen.
Ist wirklich nicht böse gemeint. Ich wollte einfach nicht, dass das Projekt wieder stirbt.
Ich persönlich interessiere mich auch mehr für die eigentliche MPV Config, 
mit dem drumrum muss ich mich später auseinandersetzen...
Ich versuche erst einmal ein wenig einen Überblick zu bekommen

Makin hatte sich daher Deiner Anleitung angenommen hier und es ist letztlich auch nur ein Fork.
(Einen weiteren Fork gibt es afaik auch bei GoogleDocs?)

Ich werde makin bitten, Deine Anleitung passend zu benennen, wäre das ok für Dich?
Oder stört Dich, dass HKV im Projektnamen hier steht?

Du bist natürlich herzlich eingeladen Dich uns hier anzuschließen.
(Disclaimer: mit dem HKV hat das hier nichts zu tun, die Idee ist halt nur aus dem Thread entstanden...)

Englisch:
hatten wir auch kurz überlegt, es aber hinten angestellt.... 
erst einmal auf deutsch schauen ob etwas Sinnvolles & Nutzbares bei rum kommt.
(auf deutsch geht es halt erst mal flotter von der Hand....)
Das übersetzen wäre dann hinterher ja kein Problem

P.S. kann man hier bei github eigentlich auch PNs versenden?

**Comment by kmpc-makin** [comment]
Habe es im Wiki umbenannt. Weiß nicht, ob Du im Forum noch mitliest, aber das war, wie du schon angemerkt hast, keinesfalls böse gemeint. Sorry fürs auf den Schlips treten.

**Comment by mr-berndt** [comment]
Einen Fork gibt es nicht bei einem Dokument, das kann man nur kopieren. Das darf man für private Zwecke ja auch und es ist ja auch meine Idee gewesen. Was natürlich nicht meine Idee war, ist, dass das Ding dann als HKV Eigentum auftaucht, aber das habt ihr ja geklärt und damit ist das auch in Ordnung.

**Comment by kmpc-makin** [comment]
Passt es so sicher für dich? Möchte hier keinesfalls irgendwie böses Blut. Und geht es letztendlich darum hier eine Art Wissensdatenbank zu schaffen und zwar auf neutralem Boden. Und Heiko und ich hielten ein git da für passend. 😊

**Comment by GittyBaer** [comment]
Dann ist ja alles geklärt :-)
Um es von meiner Seite auch noch einmal klarzustellen: 
Das Repository und auch ich haben mit dem HKV nichts zu tun. (davon ab, dass ich einen Account in dessen Forum habe ;-))
Der Name war da vielleicht von mir unglücklich gewählt...sorry.
Es basiert halt zum Teil aus den Infos aus besagtem Thread.
Meine brainstorming Dokumentations.txt ist aber mittlerweile aus diversen Quellen im Netz zusammen kopiert....

Lust Dich uns hier anzuschließen hast Du nicht, oder?

**Comment by mr-berndt** [comment]
Alles gut, ich schließe mich weder ein noch aus. Wenn ich etwas beizutragen habe, werde ich das gerne tun. Es ist nur die große Frage, ob die Plattform Github dafür geeignet ist, aber man wird ja sehen, was kommt.

**Comment by kmpc-makin** [comment]
Ok super. Also wenn Du eine alternative Idee für git hast, nur her damit. :-)

**Comment by GittyBaer** [comment]
+1 ...war halt das erst beste was mir einfiel, was kostenlos und direkt verfügbar ist.

**Comment by mr-berndt** [comment]
Wenn Ihr Euch vertrauensvoll an Olombo wendest, gibt der Euch gerne meine Kontaktdaten, dann könnten wir mal gemeinsam überlegen, wo man sich gut austauschen könnte.

**Comment by GittyBaer** [comment]
Perfekt! :-)
...(irgendwie bekomme ich von github immer erst einen Tag später eine Nachricht, über die Nachrichten hier ^^ )
